### ISSUE TITLE
about Demo

### ISSUE THREAD

**Issue by yyssmm** [YirongMao/NAN#1]
hello, thank you for sharing your code. Would you please provide a demo or a pre_trained model for test? thanks!

**Comment by YirongMao** [comment]
> hello, thank you for sharing your code. Would you please provide a demo or a pre_trained model for test? thanks!

Thanks for your interest. You can download the pre-trained model from Baidu online drive (https://pan.baidu.com/s/1a1VXZ6sBEibLMp88cU8tnQ#list/path=%2F)

**Comment by yyssmm** [comment]
@YirongMao  Thank you very much. I will have a try.

**Comment by YirongMao** [comment]
> hello, thank you for sharing your code. Would you please provide a demo or a pre_trained model for test? thanks!

Moreover, the source code of resnet-34 is provided in my another project, please refer to https://github.com/YirongMao/COSONet/blob/master/resnet.py. The link of Baidu online drive includes images of WebFace and IJB-A datasets, and the resnet-34 pre-trained model this project used.
