### ISSUE TITLE
Is there any other way to get step 1 file(resnet34_feat.zip)?

### ISSUE THREAD

**Issue by eastsky0614** [YirongMao/NAN#2]
Hello, I study Face Recognition and I'm interested in the paper 'NAN'. So, I'm looking for some open sources about this paper and I come in your github. 

First of all, Thank you for sharing your code. But, I have a problem with using your source code. The problem is that I can't download step 1 file(resnet34_feat.zip) from baidu website. I should login that website when I download the file. But, I can join that website. Because I have no cell phone in China. 

So, Could you let me know another way to get that file(I already refer your github 'COSENet', But, I don't know How to get resnet34_feat.zip from that source) or send me by email(My email address is 92dongho@naver.com or dongho92@postech.ac.kr)?

Hope you have a nice day!
Thank you.

**Comment by YirongMao** [comment]
> Hello, I study Face Recognition and I'm interested in the paper 'NAN'. So, I'm looking for some open sources about this paper and I come in your github.
> 
> First of all, Thank you for sharing your code. But, I have a problem with using your source code. The problem is that I can't download step 1 file(resnet34_feat.zip) from baidu website. I should login that website when I download the file. But, I can join that website. Because I have no cell phone in China.
> 
> So, Could you let me know another way to get that file(I already refer your github 'COSENet', But, I don't know How to get resnet34_feat.zip from that source) or send me by email(My email address is [92dongho@naver.com](mailto:92dongho@naver.com) or [dongho92@postech.ac.kr](mailto:dongho92@postech.ac.kr))?
> 
> Hope you have a nice day!
> Thank you.

Sorry for my late response. You can download the data from the link of https://1drv.ms/u/s!As-0B0Wcu9-Rgft22c2yfmqFdvm-AA?e=USmQLM
