### ISSUE TITLE
Can the first training network used to get the features be sent the code?

### ISSUE THREAD

**Issue by mmzhang012** [YirongMao/NAN#5]
Hello, author.I recently wanted to make changes to the first network part of this code.But I don't know how the ResNet34 network is implemented in your code. Is it convenient for you to send the ResNet34 network implementation code?

**Comment by YirongMao** [comment]
> Hello, author.I recently wanted to make changes to the first network part of this code.But I don't know how the ResNet34 network is implemented in your code. Is it convenient for you to send the ResNet34 network implementation code?

Thanks for your interest. My backbone network is borrowed from torchvision:
https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py

**Comment by mmzhang012** [comment]
> > Hello, author.I recently wanted to make changes to the first network part of this code.But I don't know how the ResNet34 network is implemented in your code. Is it convenient for you to send the ResNet34 network implementation code?
> 
> Thanks for your interest. My backbone network is borrowed from torchvision:
> https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py

Thank you very much for your reply! But I'm still confused.  I don't know how to write the code for the data passing in and the result saving part. Can I have the honor to get your training source code? Thank you again for taking time out of your busy schedule to reply me!

**Comment by YirongMao** [comment]
> > > Hello, author.I recently wanted to make changes to the first network part of this code.But I don't know how the ResNet34 network is implemented in your code. Is it convenient for you to send the ResNet34 network implementation code?
> > 
> > 
> > Thanks for your interest. My backbone network is borrowed from torchvision:
> > https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
> 
> Thank you very much for your reply! But I'm still confused. I don't know how to write the code for the data passing in and the result saving part. Can I have the honor to get your training source code? Thank you again for taking time out of your busy schedule to reply me!
As for training face recognition backbone network,  you can refer to Insightface project: https://github.com/deepinsight/insightface

**Comment by YirongMao** [comment]
> > > Hello, author.I recently wanted to make changes to the first network part of this code.But I don't know how the ResNet34 network is implemented in your code. Is it convenient for you to send the ResNet34 network implementation code?
> > 
> > 
> > Thanks for your interest. My backbone network is borrowed from torchvision:
> > https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
> 
> Thank you very much for your reply! But I'm still confused. I don't know how to write the code for the data passing in and the result saving part. Can I have the honor to get your training source code? Thank you again for taking time out of your busy schedule to reply me!

As for training face recognition backbone, you can refer to Insightface project: https://github.com/deepinsight/insightface
